# Generated by Django 5.2.4 on 2025-07-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_alter_product_category_alter_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
